classes:
  - myorg.apps.staging.app1

parameters:
  target_name: app1-deploy2
  application:
    source:
      helm:
        parameters: 
          - name: env.LOG_LEVEL
            value: DEBUG
    secret:
      DB_HOST: ?{vaultkv:staging/database/hostname}
      DB_NAME: ?{vaultkv:staging/database/username}
      DB_PASS: ?{vaultkv:staging/database/password}

