apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: app1-deploy2
  namespace: argocd
spec:
  destination:
    namespace: project1
    server: https://k8s-api.us.mydomain.com
  project: proj1
  source:
    helm:
      parameters:
        - name: env.LOG_LEVEL
          value: DEBUG
    path: chart
    repoURL: git@github.com:myorg/app1.git
    targetRevision: master
