apiVersion: v1
kind: Secret
metadata:
  labels:
    tesoro.kapicorp.com: enabled
  name: app1-deploy2
  namespace: project1
stringData:
  DB_HOST: ?{vaultkv:eyJkYXRhIjogImMyaGhjbVZrTFdOeVpXUnpMM1Z6TDJkc2IySmhiQzkyWVhKek9rZE1UMEpCVEY5RVFsOUlUMU5VQ2c9PSIsICJlbmNvZGluZyI6ICJvcmlnaW5hbCIsICJ0eXBlIjogInZhdWx0a3YiLCAidmF1bHRfcGFyYW1zIjogeyJWQVVMVF9BRERSIjogImh0dHBzOi8vdmF1bHQudXMudGVhbXdvcmtvcHMuY29tIiwgIlZBVUxUX1NLSVBfVkVSSUZZIjogdHJ1ZSwgImF1dGgiOiAidG9rZW4iLCAiZW5naW5lIjogImt2LXYyIn19:embedded}
  DB_NAME: ?{vaultkv:eyJkYXRhIjogImMyaGhjbVZrTFdOeVpXUnpMM1Z6TDJkc2IySmhiQzkyWVhKek9rZE1UMEpCVEY5RVFsOVZVMFZTQ2c9PSIsICJlbmNvZGluZyI6ICJvcmlnaW5hbCIsICJ0eXBlIjogInZhdWx0a3YiLCAidmF1bHRfcGFyYW1zIjogeyJWQVVMVF9BRERSIjogImh0dHBzOi8vdmF1bHQudXMudGVhbXdvcmtvcHMuY29tIiwgIlZBVUxUX1NLSVBfVkVSSUZZIjogdHJ1ZSwgImF1dGgiOiAidG9rZW4iLCAiZW5naW5lIjogImt2LXYyIn19:embedded}
  DB_PASS: ?{vaultkv:eyJkYXRhIjogImMyaGhjbVZrTFdOeVpXUnpMM1Z6TDJkc2IySmhiQzkyWVhKek9rZE1UMEpCVEY5RVFsOVFRVk5UQ2c9PSIsICJlbmNvZGluZyI6ICJvcmlnaW5hbCIsICJ0eXBlIjogInZhdWx0a3YiLCAidmF1bHRfcGFyYW1zIjogeyJWQVVMVF9BRERSIjogImh0dHBzOi8vdmF1bHQudXMudGVhbXdvcmtvcHMuY29tIiwgIlZBVUxUX1NLSVBfVkVSSUZZIjogdHJ1ZSwgImF1dGgiOiAidG9rZW4iLCAiZW5naW5lIjogImt2LXYyIn19:embedded}
type: Opaque
