apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: crmcore-staging
  namespace: argocd
spec:
  destination:
    namespace: crm
    server: https://k8s-api.staging.mydomain.com
  project: crm
  source:
    helm:
      values: "crmcore:\n  service:\n    serviceType: LoadBalancer\n    hostname:\
        \ crmcore.us.mydomain.com\n    sslCertArn: arn:aws:acm:us-east-1:XXXXXXXXXXXXXX:certificate/aaaaa-bbbb-cccc-dddd-eeee\n\
        \  env:\n    ENV: prod\n    LOG_DEBUG: false\n    SENTRY_ENABLED: true\n \
        \   SENTRY_DSN: https://XXXXXX:YYYYYYY@sentry.io/ZZZZZZ\n    SENTRY_ENVIRONMENT:\
        \ production\n"
    path: deployment/crmcore
    repoURL: git@github.com:Teamwork/crmcore.git
    targetRevision: staging
