classes:
  - common

parameters:
  argocd:
    namespace: argocd

  kapitan:
    compile:
      - output_path: .
        input_type: jsonnet
        output_type: yaml
        input_paths:
          - templates/argocd/application.jsonnet
          - templates/argocd/application/secret.jsonnet

